# Walrus site deployment configuration
# Contains package addresses and deployment settings for both networks
contexts:
  testnet:
    # Walrus Sites package on testnet
    package: 0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799
    staking_object: 0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3
    general:
      wallet_env: testnet
      walrus_context: testnet
      # Walrus storage package on testnet
      walrus_package: 0xd84704c17fc870b8764832c535aa6b11f21a95cd6f5bb38a9b07d2cf42220c66
      # These paths will be set by the workflow
      # wallet_address: injected from secrets
      # rpc_url: from client config
      # wallet: ~/.sui/sui_config/client.yaml
      # walrus_binary: /usr/local/bin/walrus
      # walrus_config: ~/.config/walrus/client_config.yaml
      # gas_budget: 500000000
  mainnet:
    # Walrus Sites package on mainnet
    package: 0x26eb7ee8688da02c5f671679524e379f0b837a12f1d1d799f255b7eea260ad27
    staking_object: 0x10b9d30c28448939ce6c4d6c6e0ffce4a7f8a4ada8248bdad09ef8b70e4a3904
    general:
      wallet_env: mainnet
      walrus_context: mainnet
      # Walrus storage package on mainnet
      walrus_package: 0xfdc88f7d7cf30afab2f82e8380d11ee8f70efb90e863d1de8616fae1bb09ea77
      # These paths will be set by the workflow
      # wallet_address: injected from secrets
      # rpc_url: from client config
      # wallet: ~/.sui/sui_config/client.yaml
      # walrus_binary: /usr/local/bin/walrus
      # walrus_config: ~/.config/walrus/client_config.yaml
      # gas_budget: 500000000
default_context: testnet
